import getRandomTimeStamp from "../helpers/getRandomTimeStamp";

export const comments = {
  cid_111: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 2,
    isCommentLiked: false,
    childComments: ["ccid_111", "ccid_112"],
    userWhoCommented: "matrix_victor",
  },
  cid_112: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 23,
    isCommentLiked: false,
    childComments: ["ccid_211"],
    userWhoCommented: "gojo_kun",
  },
  cid_113: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 4,
    isCommentLiked: false,
    childComments: [],
    userWhoCommented: "vk_76",
  },
  cid_211: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 0,
    isCommentLiked: false,
    childComments: [],
    userWhoCommented: "matrix_victor",
  },
  cid_212: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 1000,
    isCommentLiked: false,
    childComments: ["ccid_311"],
    userWhoCommented: "gojo_kun",
  },
  cid_213: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 45,
    isCommentLiked: false,
    childComments: [],
    userWhoCommented: "vk_76",
  },
  cid_311: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 4,
    isCommentLiked: false,
    childComments: [],
    userWhoCommented: "gojo_kun",
  },
  cid_312: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 65000,
    isCommentLiked: false,
    childComments: [],
    userWhoCommented: "matrix_victor",
  },
  cid_313: {
    body: "Nisi eiusmod eu minim proident.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 45000,
    isCommentLiked: false,
    userWhoCommented: "vk_76",
  },
  ccid_111: {
    body: "Cillum eiusmod in nisi ullamco ullamco commodo consectetur ex sint et pariatur.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 10,
    isCommentLiked: false,
    userWhoCommented: "gojo_kun",
  },
  ccid_112: {
    body: "Reprehenderit nisi magna exercitation id dolor magna aute culpa.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 4,
    isCommentLiked: false,
    userWhoCommented: "vk_76",
  },
  ccid_211: {
    body: "Commodo deserunt quis aliquip enim non voluptate amet ex veniam sunt in.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 5,
    isCommentLiked: false,
    userWhoCommented: "matrix_victor",
  },
  ccid_311: {
    body: "Ipsum irure elit officia quis magna enim.",
    timeStamp: getRandomTimeStamp(new Date(2012, 0, 1), new Date()),
    likes: 1,
    isCommentLiked: false,
    userWhoCommented: "gojo_kun",
  },
};
